import crypto from 'node:crypto';

import { TEMPLATE } from '../core/templates.js';
import type { Feature } from '../core/types.js';
import { usesDrizzle } from '../core/types.js';

const EXAMPLE_HEADER = `# Since the ".env" file is gitignored, you can use the ".env.example" file to
# build a new ".env" file when you clone the repo. Keep this file up-to-date
# when you add new variables to \`.env\`.
#
# This file will be committed to version control, so make sure not to have any
# secrets in it. If you are cloning this repo, create a copy of this file named
# ".env" and populate it with your secrets.

# When adding additional environment variables, the schema in "/src/env.js"
# should be updated accordingly.
`;

function databaseEnvBlock(provider: 'postgres' | 'neon', scopedName: string): string {
  if (provider === 'neon') {
    return `
# Drizzle + Neon
# Get your connection string from https://console.neon.tech
DATABASE_URL="postgresql://user:password@ep-example.us-east-1.aws.neon.tech/${scopedName}?sslmode=require"
`;
  }

  return `
# Drizzle + PostgreSQL (local)
DATABASE_URL="postgresql://postgres:password@localhost:5432/${scopedName}"
`;
}

export const envFeature: Feature = {
  id: 'env',
  apply(project) {
    const { auth } = project.stack;

    let schemaTemplate: string | undefined;
    if (usesDrizzle(project.stack) && auth) schemaTemplate = TEMPLATE.env.authDb;
    else if (usesDrizzle(project.stack)) schemaTemplate = TEMPLATE.env.db;
    else if (auth) schemaTemplate = TEMPLATE.env.auth;

    if (schemaTemplate) {
      project.copyRaw(schemaTemplate, 'src/env.js');
    }

    const secret = Buffer.from(crypto.getRandomValues(new Uint8Array(32))).toString(
      'base64',
    );
    let body = '';

    if (auth) {
      body += `
# Better Auth
BETTER_AUTH_SECRET=""
`;
    }

    if (usesDrizzle(project.stack)) {
      body += databaseEnvBlock(project.drizzleProvider, project.scopedName);
    }

    if (!auth && !usesDrizzle(project.stack)) {
      body += `
# Example:
# SERVERVAR="foo"
# NEXT_PUBLIC_CLIENTVAR="bar"
`;
    }

    const example = `${EXAMPLE_HEADER}${body}`;
    const env = body
      .replace(
        'BETTER_AUTH_SECRET=""',
        `BETTER_AUTH_SECRET="${secret}" # Generated by @madda/app.`,
      )
      .replace('AUTH_SECRET=""', `AUTH_SECRET="${secret}" # Generated by @madda/app.`);

    project.write('.env.example', example);
    project.write('.env', env.trimStart());
  },
};
