import crypto from 'node:crypto';

import { TEMPLATE } from '../core/templates.js';
import type { Feature } from '../core/types.js';
import { usesDrizzle } from '../core/types.js';

const EXAMPLE_HEADER = `# Since the ".env" file is gitignored, you can use the ".env.example" file to
# build a new ".env" file when you clone the repo. Keep this file up-to-date
# when you add new variables to \`.env\`.
#
# This file will be committed to version control, so make sure not to have any
# secrets in it. If you are cloning this repo, create a copy of this file named
# ".env" and populate it with your secrets.

# When adding additional environment variables, the schema in "/src/env.js"
# should be updated accordingly.
`;

const WEBSERVER_ENV_BLOCK = `
# Webserver
NEXT_PUBLIC_WEBSERVER_HOST="localhost"
NEXT_PUBLIC_WEBSERVER_PORT="3000"
`;

const LOGGING_ENV_BLOCK = `
# Logging (optional — used in preview/production with Axiom)
# LOG_LEVEL="warn"
# AXIOM_DATASET=""
# AXIOM_TOKEN=""
# AXIOM_URL="https://api.axiom.co"
# AXIOM_ORG_ID=""
`;

function databaseEnvBlock(provider: 'postgres' | 'neon', scopedName: string): string {
  if (provider === 'neon') {
    return `
# Drizzle + Neon
# Get your connection string from https://console.neon.tech
DATABASE_URL="postgresql://user:password@ep-example.us-east-1.aws.neon.tech/${scopedName}?sslmode=require"
`;
  }

  return `
# Drizzle + PostgreSQL (local)
DATABASE_URL="postgresql://postgres:password@localhost:5432/${scopedName}"
`;
}

function authEnvBlock(withDrizzle: boolean, scopedName: string): string {
  if (withDrizzle) {
    return `
# Better Auth
APP_NAME="${scopedName}"
BETTER_AUTH_SECRET=""
BETTER_AUTH_URL="http://localhost:3000"
BETTER_BASE_PATH="/api/v1/auth"
GOOGLE_CLIENT_ID=""
GOOGLE_CLIENT_SECRET=""
TRUSTED_ORIGINS="http://localhost:3000"

# Client
NEXT_PUBLIC_APP_URL="http://localhost:3000"
NEXT_PUBLIC_BETTER_BASE_PATH="/api/v1/auth"
`;
  }

  return `
# Better Auth
BETTER_AUTH_SECRET=""
BETTER_AUTH_GITHUB_CLIENT_ID=""
BETTER_AUTH_GITHUB_CLIENT_SECRET=""
`;
}

export const envFeature: Feature = {
  id: 'env',
  apply(project) {
    const { auth } = project.stack;
    const withDrizzle = usesDrizzle(project.stack);

    let schemaTemplate: string | undefined;
    if (withDrizzle && auth) schemaTemplate = TEMPLATE.env.authDb;
    else if (withDrizzle) schemaTemplate = TEMPLATE.env.db;
    else if (auth) schemaTemplate = TEMPLATE.env.auth;

    if (schemaTemplate) {
      project.copyRaw(schemaTemplate, 'src/env.js');
    }

    const secret = Buffer.from(crypto.getRandomValues(new Uint8Array(32))).toString(
      'base64',
    );

    let body = WEBSERVER_ENV_BLOCK + LOGGING_ENV_BLOCK;

    if (auth) {
      body += authEnvBlock(withDrizzle, project.scopedName);
    }

    if (withDrizzle) {
      body += databaseEnvBlock(project.drizzleProvider, project.scopedName);
    }

    const example = `${EXAMPLE_HEADER}${body}`;
    const env = body.replace(
      'BETTER_AUTH_SECRET=""',
      `BETTER_AUTH_SECRET="${secret}" # Generated by @madda/app.`,
    );

    project.write('.env.example', example);
    project.write('.env', env.trimStart());
  },
};
